---
chapter: "algorithmic"
author: "Ben Baumer"
difficulty: "Easy"
date: 2020-08-09 
version: 0.1
tags: [functions, exceptions]
id: ash-lose-tv
---

```{r ash-lose-tv-default, include = FALSE}
library(tidyverse)
mdsr2exercises::setup()
```

TITLE GOES HERE: Consider the following function definition, and subsequent call of that function. 

```{r, error=TRUE, message=FALSE}
library(tidyverse)

summarize_species <- function(pattern = "Human") {
  x <- starwars |>
    filter(species == pattern) |>
    summarize(
      num_people = n(),
      avg_height = mean(height, na.rm = TRUE)
    )
}

summarize_species("Wookiee")
x
```

What causes this error? 

<!--answer-start-->
`x` is a local variable that only exists within the execution of the function `summarize_species()`, and doesn't exist in the global environment. 
<!--answer-end-->



